import { invoke } from "@tauri-apps/api/core";
import { listen } from "@tauri-apps/api/event";
import * as ScrollAreaPrimitive from "@radix-ui/react-scroll-area";
import * as TabsPrimitive from "@radix-ui/react-tabs";
import * as TooltipPrimitive from "@radix-ui/react-tooltip";
import { useCallback, useEffect, useRef, useState, type MouseEvent } from "react";
import { parseMarkdownSections, parseMarkdownTable, parseScopedMarkdownTable, splitTabbedDocument, type SlateSourceDefinition } from "./index.js";
import { clearSlateFavoriteSourceIds, describeSlateView, isSlateTauriRuntime, keepLatestSnapshot, loadSlateFavoriteSourceIds, openSlateExternalUrl, parseInlineMarkdown, partitionSlateSources, releaseIfDisposed, retainSelectedSource, saveSlateFavoriteSourceIds, shouldRefreshSource, slateDemoSnapshots, slateDemoSources, slateHeadingTag, slateLinkTarget, sortTableRows, toggleSlateFavoriteSourceId, validateSourceMetadata, type SlateSnapshot, type SlateSourceChange, type TableSortDirection } from "./pluginModel.js";

type Source = Pick<SlateSourceDefinition, "id" | "label" | "view">;
const configFile = "slate.config.json";
export type WorkspaceRootRequestResult = { ok: true } | { ok: false; message: string };
export type WorkshopToolViewProps = { activeRouteId?: string; workspaceRoot?: string; requestWorkspaceRoot: (root: string) => WorkspaceRootRequestResult | void; clearWorkspaceRoot?: () => void };

export function WorkshopToolView({ workspaceRoot, requestWorkspaceRoot, clearWorkspaceRoot }: WorkshopToolViewProps) {
  const [root, setRoot] = useState(""); const [sources, setSources] = useState<Source[]>([]); const [selected, setSelected] = useState<string>();
  const [data, setData] = useState<Record<string, SlateSnapshot>>({}); const [error, setError] = useState<string>(); const [favoriteIds, setFavoriteIds] = useState<string[]>(() => loadSlateFavoriteSourceIds(slateLocalStorage(), workspaceRoot ?? "")); const versions = useRef<Record<string, number>>({});
  useEffect(() => { setFavoriteIds(loadSlateFavoriteSourceIds(slateLocalStorage(), workspaceRoot ?? "")); }, [workspaceRoot]);
  const read = useCallback(async (id: string, active: () => boolean = () => true) => { if (!workspaceRoot) return; const version = (versions.current[id] ?? 0) + 1; versions.current[id] = version; try { const result = await invoke<SlateSnapshot>("read_configured_markdown_source", { workspaceRoot, configFile, source: id }); if (!active()) return; setData((old) => keepLatestSnapshot(old, id, version, versions.current[id], result)); if (versions.current[id] === version) setError(undefined); } catch (cause) { if (active() && versions.current[id] === version) setError(cause instanceof Error ? cause.message : "Slate could not read this source."); } }, [workspaceRoot]);
  useEffect(() => { if (!workspaceRoot) return; let disposed = false; let stop: (() => void) | undefined; const active = () => !disposed; void (async () => { try { const raw = await invoke<unknown>("read_configured_markdown_sources", { workspaceRoot, configFile }); if (!active()) return; const listed = validateSourceMetadata(raw); if (!listed) throw new Error("Slate configuration contains unsupported source metadata."); setSources(listed); setSelected((old) => retainSelectedSource(old, listed)); await Promise.all(listed.map((source) => read(source.id, active))); if (!active()) return; const lateStop = await listen<SlateSourceChange>("local-markdown://source-changed", (event) => { if (shouldRefreshSource(workspaceRoot, event.payload, configFile)) void read(event.payload.source, active); }); if (releaseIfDisposed(disposed, lateStop)) return; stop = lateStop; await invoke("start_configured_markdown_watch", { workspaceRoot, configFile }); } catch (cause) { if (active()) setError(cause instanceof Error ? cause.message : "Slate could not load its private configuration."); } })(); return () => { disposed = true; stop?.(); }; }, [workspaceRoot, read]);
  if (!workspaceRoot && isBrowserPreview() && !isSetupPreview()) return <DemoSlate />;
  if (!workspaceRoot) return <main className="slate-plugin"><SlateStyles /><SlateWorkspaceSetup initialRoot={root} onRootChange={setRoot} requestWorkspaceRoot={requestWorkspaceRoot} /></main>;
  const source = sources.find((item) => item.id === selected); return <main className="slate-plugin"><SlateStyles />{source ? <SourceDocument source={source} snapshot={data[source.id]} onBack={() => setSelected(undefined)} /> : <SourcePicker sources={sources} favoriteIds={favoriteIds} onSelect={setSelected} onToggleFavorite={(id) => setFavoriteIds((current) => { const next = toggleSlateFavoriteSourceId(current, id); saveSlateFavoriteSourceIds(slateLocalStorage(), workspaceRoot, next); return next; })} workspaceRoot={workspaceRoot} requestWorkspaceRoot={requestWorkspaceRoot} clearWorkspaceRoot={clearWorkspaceRoot} />}{error && <p className="slate-plugin-error" role="alert">{error}</p>}</main>;
}
function DemoSlate() { const [selected, setSelected] = useState<string>(); const [favoriteIds, setFavoriteIds] = useState<string[]>(() => loadSlateFavoriteSourceIds(slateLocalStorage(), "slate-demo")); const source = slateDemoSources.find((item) => item.id === selected); return <main className="slate-plugin"><SlateStyles />{source ? <SourceDocument source={source} snapshot={slateDemoSnapshots[source.id]} onBack={() => setSelected(undefined)} /> : <><SourcePicker sources={slateDemoSources} favoriteIds={favoriteIds} onSelect={setSelected} onToggleFavorite={(id) => setFavoriteIds((current) => { const next = toggleSlateFavoriteSourceId(current, id); saveSlateFavoriteSourceIds(slateLocalStorage(), "slate-demo", next); return next; })} /><p className="slate-plugin-demo">Preview data — native Workshop uses only your configured local files.</p></>}</main>; }
function slateLocalStorage() { try { return typeof window === "undefined" ? undefined : window.localStorage; } catch { return undefined; } }
function isSetupPreview(): boolean { return typeof window !== "undefined" && new URLSearchParams(window.location.search).has("setup"); }
function SlateWorkspaceSetup({ initialRoot, onRootChange, requestWorkspaceRoot, onCancel }: { initialRoot: string; onRootChange: (root: string) => void; requestWorkspaceRoot: (root: string) => WorkspaceRootRequestResult | void; onCancel?: () => void }) { const [candidate, setCandidate] = useState(initialRoot); const [message, setMessage] = useState<string>(); const connect = () => { if (!candidate.trim()) { setMessage("Enter the folder path first."); return; } const result = requestWorkspaceRoot(candidate.trim()); if (result && !result.ok) { setMessage(result.message); return; } setMessage(undefined); onRootChange(candidate); }; return <section className="slate-plugin-workspace-setup" aria-labelledby="slate-folder-heading"><header className="slate-plugin-header"><p>Slate · local reference desk</p><h1 id="slate-folder-heading">{onCancel ? "Use a different folder" : "Connect a Slate folder"}</h1></header><p className="slate-plugin-workspace-lede">{onCancel ? "Replace the current private Slate folder." : "Choose the private folder that holds this Slate setup."}</p><label className="slate-plugin-workspace-field"><span>Folder containing slate.config.json</span><input aria-label="Folder containing slate.config.json" value={candidate} onChange={(event) => { setCandidate(event.target.value); onRootChange(event.target.value); }} placeholder="/absolute/path/to/slate" /></label><p className="slate-plugin-workspace-note">The folder must already contain <code>slate.config.json</code>. Slate does not search this folder or create files in it.</p>{message ? <p className="slate-plugin-error" role="alert">{message}</p> : null}<div className="slate-plugin-workspace-actions"><button className="slate-plugin-workspace-connect" onClick={connect}>Connect folder</button>{onCancel ? <button className="slate-plugin-workspace-cancel" onClick={onCancel}>Cancel</button> : null}</div></section>; }
function SlateWorkspaceDisconnect({ onConfirm, onCancel }: { onConfirm: () => void; onCancel: () => void }) { return <section className="slate-plugin-workspace-setup" aria-labelledby="slate-disconnect-heading"><header className="slate-plugin-header"><p>Slate · local reference desk</p><h1 id="slate-disconnect-heading">Disconnect Slate folder?</h1></header><p className="slate-plugin-workspace-lede">Slate will forget this folder's path on this computer.</p><p className="slate-plugin-workspace-note">The folder and its Markdown files will not change. You can reconnect it later.</p><div className="slate-plugin-workspace-actions"><button className="slate-plugin-workspace-disconnect" onClick={onConfirm}>Disconnect folder</button><button className="slate-plugin-workspace-cancel" onClick={onCancel}>Cancel</button></div></section>; }
function SourcePicker({ sources, favoriteIds, onSelect, onToggleFavorite, workspaceRoot, requestWorkspaceRoot, clearWorkspaceRoot }: { sources: Source[]; favoriteIds: string[]; onSelect: (id: string) => void; onToggleFavorite: (id: string) => void; workspaceRoot?: string; requestWorkspaceRoot?: (root: string) => WorkspaceRootRequestResult | void; clearWorkspaceRoot?: () => void }) { const [changingWorkspace, setChangingWorkspace] = useState(false); const [disconnectingWorkspace, setDisconnectingWorkspace] = useState(false); const [candidateRoot, setCandidateRoot] = useState(workspaceRoot ?? ""); const groups = partitionSlateSources(sources, favoriteIds); if (changingWorkspace && requestWorkspaceRoot) return <SlateWorkspaceSetup initialRoot={candidateRoot} onRootChange={setCandidateRoot} requestWorkspaceRoot={requestWorkspaceRoot} onCancel={() => setChangingWorkspace(false)} />; if (disconnectingWorkspace && clearWorkspaceRoot) return <SlateWorkspaceDisconnect onConfirm={() => { clearSlateFavoriteSourceIds(slateLocalStorage(), workspaceRoot ?? ""); clearWorkspaceRoot?.(); }} onCancel={() => setDisconnectingWorkspace(false)} />; return <><header className="slate-plugin-header slate-plugin-source-header"><div><p>Slate · local reference desk</p><h1>Slate</h1></div>{requestWorkspaceRoot ? <div className="slate-plugin-workspace-tools"><button className="slate-plugin-change-workspace" onClick={() => setChangingWorkspace(true)}>Change Slate folder</button>{clearWorkspaceRoot ? <button className="slate-plugin-disconnect-workspace" onClick={() => setDisconnectingWorkspace(true)}>Disconnect</button> : null}</div> : null}</header>{groups.favorites.length ? <SourceGroup label="Favorites" sources={groups.favorites} favoriteIds={favoriteIds} onSelect={onSelect} onToggleFavorite={onToggleFavorite} /> : null}{groups.documents.length ? <SourceGroup label={groups.favorites.length ? "All documents" : undefined} sources={groups.documents} favoriteIds={favoriteIds} onSelect={onSelect} onToggleFavorite={onToggleFavorite} /> : null}</>; }
function SourceGroup({ label, sources, favoriteIds, onSelect, onToggleFavorite }: { label?: string; sources: Source[]; favoriteIds: string[]; onSelect: (id: string) => void; onToggleFavorite: (id: string) => void }) { return <section className="slate-plugin-source-group" aria-label={label}>{label ? <h2>{label === "Favorites" ? "★ " : ""}{label}</h2> : null}<nav className="slate-plugin-sources" aria-label={label ? `Slate ${label.toLowerCase()}` : "Slate sources"}>{sources.map((source) => <SourceCard key={source.id} source={source} favorite={favoriteIds.includes(source.id)} onSelect={onSelect} onToggleFavorite={onToggleFavorite} />)}</nav></section>; }
function SourceCard({ source, favorite, onSelect, onToggleFavorite }: { source: Source; favorite: boolean; onSelect: (id: string) => void; onToggleFavorite: (id: string) => void }) { const view = describeSlateView(source.view); return <article className="slate-plugin-source-card"><button className="slate-plugin-source-open" onClick={() => onSelect(source.id)}><span className="slate-plugin-source-glyph" aria-hidden="true">{view.glyph}</span><span className="slate-plugin-source-copy"><strong>{source.label}</strong><small>{view.description}</small></span></button><button className="slate-plugin-source-favorite" aria-label={favorite ? `Remove ${source.label} from favorites` : `Add ${source.label} to favorites`} aria-pressed={favorite} onClick={() => onToggleFavorite(source.id)} title={favorite ? "Remove from favorites" : "Add to favorites"}><span aria-hidden="true">{favorite ? "★" : "☆"}</span></button></article>; }
function SourceDocument({ source, snapshot, onBack }: { source: Source; snapshot?: SlateSnapshot; onBack: () => void }) { return <><header className="slate-plugin-header"><p>Slate · local reference desk</p><h1>{source.label}</h1></header><button className="slate-plugin-back" onClick={onBack}>‹ Slate</button><div className="slate-plugin-panel-heading slate-plugin-panel-heading-meta"><LastEdited updatedAt={snapshot?.updatedAt} /></div><View source={source} snapshot={snapshot} /></>; }
function LastEdited({ updatedAt }: { updatedAt?: number }) { if (!updatedAt) return null; const date = new Date(updatedAt); return <time className="slate-plugin-last-edited" dateTime={date.toISOString()}><span aria-hidden="true">◷</span> Updated {date.toLocaleString()}</time>; }
function isBrowserPreview(): boolean { return typeof window !== "undefined" && !("__TAURI_INTERNALS__" in window); }
function View({ source, snapshot }: { source?: Source; snapshot?: SlateSnapshot }) { if (!source) return <p>Awaiting configured sources.</p>; if (!snapshot) return <p>Loading…</p>; if (source.view === "table") try { return <SortableTable table={parseMarkdownTable(snapshot.contents)} />; } catch { return <p role="alert">Slate could not render this table.</p>; } const sections = parseMarkdownSections(snapshot.contents); if (source.view === "table-tabs") return <TableTabs sections={sections} />; return source.view === "markdown-tabs" ? <Tabs sections={sections} /> : <Sections sections={sections} />; }
function SortableTable({ table }: { table: ReturnType<typeof parseMarkdownTable> }) { const [sort, setSort] = useState<{ column: number; direction: TableSortDirection }>(); const rows = sort ? sortTableRows(table.rows, sort.column, sort.direction) : table.rows; const toggleSort = (column: number) => setSort((current) => current?.column === column && current.direction === "ascending" ? { column, direction: "descending" } : { column, direction: "ascending" }); return <TooltipPrimitive.Provider delayDuration={350}><ScrollAreaPrimitive.Root className="slate-plugin-table"><ScrollAreaPrimitive.Viewport className="slate-plugin-table-viewport"><table><thead><tr>{table.headers.map((header, column) => { const direction = sort?.column === column ? sort.direction : "none"; const nextDirection = direction === "ascending" ? "descending" : "ascending"; return <th key={header} aria-sort={direction}><TooltipPrimitive.Root><TooltipPrimitive.Trigger asChild><button aria-label={`Sort ${header} ${nextDirection}`} onClick={() => toggleSort(column)}>{header}<span aria-hidden="true">{direction === "ascending" ? " ↑" : direction === "descending" ? " ↓" : " ↕"}</span></button></TooltipPrimitive.Trigger><TooltipPrimitive.Portal><TooltipPrimitive.Content className="slate-plugin-tooltip" sideOffset={6}>Sort {header} {nextDirection}<TooltipPrimitive.Arrow className="slate-plugin-tooltip-arrow" /></TooltipPrimitive.Content></TooltipPrimitive.Portal></TooltipPrimitive.Root></th>; })}</tr></thead><tbody>{rows.map((row, index) => <tr key={`${row.join("-")}-${index}`}>{row.map((cell, cellIndex) => <td key={cellIndex}><InlineMarkdown value={cell} /></td>)}</tr>)}</tbody></table></ScrollAreaPrimitive.Viewport><ScrollAreaPrimitive.Scrollbar className="slate-plugin-scrollbar" orientation="horizontal"><ScrollAreaPrimitive.Thumb className="slate-plugin-scrollbar-thumb" /></ScrollAreaPrimitive.Scrollbar></ScrollAreaPrimitive.Root></TooltipPrimitive.Provider>; }
function Tabs({ sections }: { sections: ReturnType<typeof parseMarkdownSections> }) { const { intro, tabs } = splitTabbedDocument(sections); if (!tabs.length) return <Sections sections={intro} />; return <>{intro.length ? <div className="slate-plugin-tab-intro"><Sections sections={intro} /></div> : null}<TabsPrimitive.Root defaultValue={tabs[0].id}><TabsPrimitive.List className="slate-plugin-tabs" aria-label="Document sections">{tabs.map((item) => <TabsPrimitive.Trigger key={item.id} value={item.id}>{item.label}</TabsPrimitive.Trigger>)}</TabsPrimitive.List>{tabs.map((item) => <TabsPrimitive.Content key={item.id} value={item.id}><Sections sections={item.sections} /></TabsPrimitive.Content>)}</TabsPrimitive.Root></>; }
function TableTabs({ sections }: { sections: ReturnType<typeof parseMarkdownSections> }) { const { intro, tabs } = splitTabbedDocument(sections); if (!tabs.length) return <p role="alert">Slate could not find any tabbed tables in this document.</p>; return <>{intro.length ? <div className="slate-plugin-tab-intro"><Sections sections={intro} /></div> : null}<TabsPrimitive.Root defaultValue={tabs[0].id}><TabsPrimitive.List className="slate-plugin-tabs" aria-label="Document tables">{tabs.map((item) => <TabsPrimitive.Trigger key={item.id} value={item.id}>{item.label}</TabsPrimitive.Trigger>)}</TabsPrimitive.List>{tabs.map((item) => <TabsPrimitive.Content key={item.id} value={item.id}><TabTable sections={item.sections} /></TabsPrimitive.Content>)}</TabsPrimitive.Root></>; }
function TabTable({ sections }: { sections: ReturnType<typeof parseMarkdownSections> }) { const result = parseScopedMarkdownTable(sections); const summary = sections.flatMap((section) => section.paragraphs).filter((paragraph) => !paragraph.trim().startsWith("|")); return <>{summary.length ? <div className="slate-plugin-table-summary">{summary.map((paragraph, index) => <p key={index}><InlineMarkdown value={paragraph} /></p>)}</div> : null}{!result.ok ? <p className="slate-plugin-empty-table" role="status">{result.message}</p> : <SortableTable table={result.table} />}</>; }
function Sections({ sections }: { sections: ReturnType<typeof parseMarkdownSections> }) { return <div className="slate-plugin-content">{sections.map((section, index) => <Section key={`${section.heading}-${index}`} section={section} />)}</div>; }
function Section({ section }: { section: ReturnType<typeof parseMarkdownSections>[number] }) { const Heading = slateHeadingTag(section.level); const className = section.level === 1 ? "slate-plugin-main-heading" : section.level === 2 ? "slate-plugin-subheading" : "slate-plugin-minor-heading"; return <section><Heading className={className}><InlineMarkdown value={section.heading} /></Heading>{section.paragraphs.map((paragraph, item) => <p key={item}><InlineMarkdown value={paragraph} /></p>)}{section.items.length ? <ul>{section.items.map((item, itemIndex) => <li key={itemIndex}><InlineMarkdown value={item} /></li>)}</ul> : null}</section>; }
function InlineMarkdown({ value }: { value: string }) { return <>{parseInlineMarkdown(value).map((token, index) => token.type === "strong" ? <strong key={index}>{token.value}</strong> : token.type === "link" ? <SlateExternalLink key={index} href={token.href}>{token.label}</SlateExternalLink> : <span key={index}>{token.value}</span>)}</>; }
function SlateExternalLink({ href, children }: { href: string; children: string }) { const browser = typeof window === "undefined" ? undefined : window; const tauri = isSlateTauriRuntime(browser); const [error, setError] = useState<string>(); const open = async (event: MouseEvent<HTMLAnchorElement>) => { if (!tauri) return; event.preventDefault(); const message = await openSlateExternalUrl(href, (command, args) => invoke(command, args)); setError(message); }; return <><a href={href} onClick={open} rel="noreferrer" target={slateLinkTarget(browser)}>{children}</a>{error ? <span className="slate-plugin-link-error" role="alert">{error}</span> : null}</>; }
function SlateStyles() { return <style>{`
  .slate-plugin{color:#f6f3f4;max-width:1040px;padding:4px 0 96px;font:14px/1.55 Inter,ui-sans-serif,system-ui,sans-serif}
  .slate-plugin h1{font-size:32px;line-height:1.1;margin:2px 0 0;letter-spacing:-.03em}
  .slate-plugin-header{border-bottom:1px solid rgba(255,255,255,.12);padding:8px 0 13px}
  .slate-plugin-header p{color:#f81b8f;font-size:14px;font-weight:800;margin:0 0 4px;text-transform:uppercase;letter-spacing:.08em}
  .slate-plugin button{background:#171719;border:1px solid #454147;border-radius:7px;color:#f6f3f4;cursor:pointer;padding:7px 11px;font:inherit}
  .slate-plugin-source-header{align-items:end;display:flex;justify-content:space-between;gap:18px}
  .slate-plugin-workspace-tools{align-items:center;display:flex;gap:6px;margin:0 0 1px}
  .slate-plugin-change-workspace{background:transparent!important;border-color:rgba(255,229,0,.45)!important;color:#ffe500!important;font-size:12px!important;margin:0 0 1px;padding:5px 8px!important;white-space:nowrap}
  .slate-plugin-change-workspace:hover{border-color:#ffe500!important;color:#f6f3f4!important}
  .slate-plugin-disconnect-workspace{background:transparent!important;border-color:transparent!important;color:#aaa7ab!important;font-size:12px!important;padding:5px 6px!important;white-space:nowrap}
  .slate-plugin-disconnect-workspace:hover{color:#ff79b9!important}
  .slate-plugin-workspace-setup{max-width:590px;padding-top:8px}
  .slate-plugin-workspace-lede{color:#d1cdd1;font-size:16px;margin:18px 0 18px;max-width:500px}
  .slate-plugin-workspace-field{display:grid;gap:6px}
  .slate-plugin-workspace-field span{color:#f6f3f4;font-size:13px;font-weight:700}
  .slate-plugin-workspace-field input{background:#111113;border:1px solid #454147;border-radius:7px;color:#f6f3f4;font:inherit;padding:10px 11px}
  .slate-plugin-workspace-field input:focus{border-color:#ffe500;outline:2px solid rgba(255,229,0,.24);outline-offset:2px}
  .slate-plugin-workspace-note{color:#aaa7ab;font-size:12px;line-height:1.55;margin:8px 0 0;max-width:510px}
  .slate-plugin-workspace-note code{color:#f6f3f4}
  .slate-plugin-workspace-actions{display:flex;gap:8px;margin-top:16px}
  .slate-plugin-workspace-connect{background:#f81b8f!important;border-color:#f81b8f!important;color:#16000d!important;font-weight:800}
  .slate-plugin-workspace-connect:hover{background:#ff79b9!important;border-color:#ff79b9!important}
  .slate-plugin-workspace-disconnect{background:transparent!important;border-color:#ff79b9!important;color:#ff79b9!important}
  .slate-plugin-workspace-disconnect:hover{background:rgba(248,27,143,.1)!important}
  .slate-plugin-workspace-cancel{background:transparent!important;border-color:transparent!important;color:#aaa7ab!important}
  .slate-plugin-workspace-cancel:hover{color:#f6f3f4!important}
  .slate-plugin-source-group{margin:18px 0 25px}
  .slate-plugin-source-group h2{align-items:center;color:#ffe500;display:flex;font-size:13px;letter-spacing:.08em;margin:0 0 8px;text-transform:uppercase}
  .slate-plugin-sources{display:grid;gap:10px;grid-template-columns:repeat(3,minmax(0,1fr))}
  .slate-plugin-source-card{background:rgba(255,255,255,.025);border:1px solid #454147;border-radius:8px;display:grid;grid-template-columns:minmax(0,1fr) auto;min-width:0;overflow:hidden}
  .slate-plugin-source-card:hover{background:rgba(248,27,143,.08);border-color:#f81b8f}
  .slate-plugin-source-open{align-items:center;background:transparent!important;border:0!important;border-radius:0!important;display:flex;gap:11px;min-width:0;padding:12px 4px 12px 13px!important;text-align:left}
  .slate-plugin-source-open:focus-visible{outline:2px solid #ffe500;outline-offset:-3px}
  .slate-plugin-source-favorite{align-self:start;background:transparent!important;border:0!important;border-radius:0!important;color:#aaa7ab!important;font-size:21px!important;line-height:1!important;margin:7px 7px 0 0;padding:3px!important}
  .slate-plugin-source-favorite:hover,.slate-plugin-source-favorite[aria-pressed=true]{color:#ffe500!important}
  .slate-plugin-source-favorite:focus-visible{outline:2px solid #ffe500;outline-offset:0}
  .slate-plugin-source-glyph{color:#f81b8f;font-size:22px;line-height:1}
  .slate-plugin-source-copy{display:grid;gap:2px;min-width:0}
  .slate-plugin-source-copy strong{color:#f6f3f4;font-size:15px}
  .slate-plugin-source-copy small{color:#aaa7ab;font-size:12px}
  .slate-plugin-back{background:transparent!important;border:0!important;border-radius:0!important;color:#ffe500!important;margin:11px 0 0;padding:0!important}
  .slate-plugin-back:hover{color:#f6f3f4!important}
  .slate-plugin-panel-heading{align-items:center;display:flex;justify-content:space-between;gap:16px;margin-top:13px}
  .slate-plugin-panel-heading-meta{justify-content:flex-end}
  .slate-plugin-panel-heading p{color:#f6f3f4;font-size:14px;font-weight:700;margin:0}
  .slate-plugin-panel-heading span{color:#aaa7ab;font-size:12px}
  .slate-plugin-last-edited{align-items:center;color:#8e898f;display:flex;font-size:12px;gap:5px;white-space:nowrap}
  .slate-plugin-tabs{border-bottom:1px solid rgba(255,255,255,.16);display:flex;gap:4px;margin:14px 0 24px;overflow-x:auto;padding:0 3px}
  .slate-plugin-tabs button{background:transparent;border:1px solid transparent;border-bottom:0;border-radius:7px 7px 0 0;color:#aaa7ab;margin-bottom:-1px;padding:7px 11px;white-space:nowrap}
  .slate-plugin-tabs button:hover{color:#f6f3f4}
  .slate-plugin-tabs button[data-state=active]{background:#171719;border-color:rgba(255,255,255,.2);color:#ffe500;font-weight:700}
  .slate-plugin-tabs button:focus-visible{outline:2px solid #ffe500;outline-offset:3px}
  .slate-plugin-content{max-width:820px}
  .slate-plugin-panel-heading + .slate-plugin-content{margin-top:22px}
  .slate-plugin-content section{margin:0 0 20px}
  .slate-plugin-content h2{line-height:1.25;margin:0 0 6px;letter-spacing:-.03em}
  .slate-plugin-main-heading{color:#f81b8f;font-size:23px}
  .slate-plugin-subheading{color:#ffe500;font-size:17px}
  .slate-plugin-minor-heading{color:#f6f3f4;font-size:15px;font-weight:650}
  .slate-plugin-content p{color:#d1cdd1;margin:0 0 7px}
  .slate-plugin a{color:#ffe500;text-decoration-color:rgba(255,229,0,.55);text-underline-offset:2px}
  .slate-plugin a:hover{color:#f81b8f;text-decoration-color:#f81b8f}
  .slate-plugin-link-error{color:#ff79b9;display:block;font-size:12px;margin-top:4px}
  .slate-plugin-content ul{list-style:none;margin:5px 0 0;padding-left:18px}
  .slate-plugin-content li{margin:3px 0;position:relative}
  .slate-plugin-content ul li::before{color:#8e898f;content:"–";left:-15px;position:absolute}
  .slate-plugin-table-summary{color:#d1cdd1;max-width:820px}
  .slate-plugin-table-summary p{margin:0 0 8px}
  .slate-plugin-table{border:1px solid #403b42;border-radius:8px;margin-top:14px;overflow:hidden}
  .slate-plugin-table-viewport{overflow:auto}
  .slate-plugin table{border-collapse:collapse;width:100%;min-width:580px}
  .slate-plugin th,.slate-plugin td{padding:11px 10px;text-align:left;border-bottom:1px solid rgba(255,255,255,.09);vertical-align:top}
  .slate-plugin th{color:#ffe500;background:#171719;font-size:11px;letter-spacing:.06em;text-transform:uppercase;white-space:nowrap}
  .slate-plugin tbody tr:hover{background:rgba(255,255,255,.035)}
  .slate-plugin th button{appearance:none;background:transparent;border:0;border-radius:0;color:inherit;cursor:pointer;font:inherit;padding:0}
  .slate-plugin-scrollbar{background:#171719;display:flex;height:8px;padding:2px}
  .slate-plugin-scrollbar-thumb{background:#6f6870;border-radius:99px;flex:1}
  .slate-plugin-tooltip{background:#f6f3f4;border-radius:5px;color:#16000d;font-size:12px;padding:5px 7px;z-index:100}
  .slate-plugin-tooltip-arrow{fill:#f6f3f4}
  .slate-plugin-error{color:#ff79b9}
  .slate-plugin-demo{color:#aaa7ab;font-size:12px;margin:14px 0 0}
  @media (max-width:760px){.slate-plugin-sources{grid-template-columns:repeat(2,minmax(0,1fr))}}
  @media (max-width:520px){.slate-plugin-sources{grid-template-columns:1fr}.slate-plugin-source-header{align-items:start;flex-direction:column}.slate-plugin-workspace-tools{margin-top:4px}.slate-plugin-change-workspace{margin-top:0}}
`}</style>; }
