import { invoke } from "@tauri-apps/api/core";
import { listen } from "@tauri-apps/api/event";
import { useCallback, useEffect, useRef, useState } from "react";
import { buildTopLevelTabs, parseMarkdownSections, parseMarkdownTable, type SlateSourceDefinition } from "./index.js";
import { keepLatestSnapshot, shouldRefreshSource, validateSourceMetadata, type SlateSnapshot, type SlateSourceChange } from "./pluginModel.js";

type Source = Pick<SlateSourceDefinition, "id" | "label" | "view">;
const configFile = "slate.config.json";
export type WorkshopToolViewProps = { activeRouteId?: string; workspaceRoot?: string; requestWorkspaceRoot: (root?: string) => void };

export function WorkshopToolView({ workspaceRoot, requestWorkspaceRoot }: WorkshopToolViewProps) {
  const [root, setRoot] = useState(""); const [sources, setSources] = useState<Source[]>([]); const [selected, setSelected] = useState("");
  const [data, setData] = useState<Record<string, SlateSnapshot>>({}); const [error, setError] = useState<string>(); const versions = useRef<Record<string, number>>({});
  const read = useCallback(async (id: string) => { if (!workspaceRoot) return; const version = (versions.current[id] ?? 0) + 1; versions.current[id] = version; try { const result = await invoke<SlateSnapshot>("read_configured_markdown_source", { workspaceRoot, configFile, source: id }); setData((old) => keepLatestSnapshot(old, id, version, versions.current[id], result)); if (versions.current[id] === version) setError(undefined); } catch (cause) { if (versions.current[id] === version) setError(cause instanceof Error ? cause.message : "Slate could not read this source."); } }, [workspaceRoot]);
  useEffect(() => { if (!workspaceRoot) return; let stop: (() => void) | undefined; void (async () => { try { const raw = await invoke<unknown>("read_configured_markdown_sources", { workspaceRoot, configFile }); const listed = validateSourceMetadata(raw); if (!listed) throw new Error("Slate configuration contains unsupported source metadata."); setSources(listed); setSelected((old) => old && listed.some((source) => source.id === old) ? old : listed[0]?.id ?? ""); await Promise.all(listed.map((source) => read(source.id))); stop = await listen<SlateSourceChange>("local-markdown://source-changed", (event) => { if (shouldRefreshSource(workspaceRoot, event.payload, configFile)) void read(event.payload.source); }); await invoke("start_configured_markdown_watch", { workspaceRoot, configFile }); } catch (cause) { setError(cause instanceof Error ? cause.message : "Slate could not load its private configuration."); } })(); return () => stop?.(); }, [workspaceRoot, read]);
  if (!workspaceRoot) return <main><h1>Slate</h1><p>View explicitly configured local Markdown files.</p><input aria-label="Slate private folder" value={root} onChange={(event) => setRoot(event.target.value)} placeholder="/absolute/path/to/slate" /><button disabled={!root.startsWith("/")} onClick={() => requestWorkspaceRoot(root)}>Connect Slate</button></main>;
  const source = sources.find((item) => item.id === selected); return <main><header><p>Slate · local reference desk</p><h1>{source?.label ?? "Slate"}</h1></header><nav aria-label="Slate sources">{sources.map((item) => <button key={item.id} aria-current={item.id === selected ? "page" : undefined} onClick={() => setSelected(item.id)}>{item.label}</button>)}</nav>{error && <p role="alert">{error}</p>}<View source={source} snapshot={source ? data[source.id] : undefined} /></main>;
}
function View({ source, snapshot }: { source?: Source; snapshot?: SlateSnapshot }) { if (!source) return <p>Awaiting configured sources.</p>; if (!snapshot) return <p>Loading…</p>; if (source.view === "table") try { const table = parseMarkdownTable(snapshot.contents); return <table><thead><tr>{table.headers.map((header) => <th key={header}>{header}</th>)}</tr></thead><tbody>{table.rows.map((row, index) => <tr key={index}>{row.map((cell, cellIndex) => <td key={cellIndex}>{cell}</td>)}</tr>)}</tbody></table>; } catch { return <p role="alert">Slate could not render this table.</p>; } const sections = parseMarkdownSections(snapshot.contents); return source.view === "markdown-tabs" ? <Tabs sections={sections} /> : <Sections sections={sections} />; }
function Tabs({ sections }: { sections: ReturnType<typeof parseMarkdownSections> }) { const tabs = buildTopLevelTabs(sections); const [active, setActive] = useState(tabs[0]?.id); const tab = tabs.find((item) => item.id === active) ?? tabs[0]; return <><div role="tablist">{tabs.map((item) => <button role="tab" aria-selected={item.id === tab?.id} key={item.id} onClick={() => setActive(item.id)}>{item.label}</button>)}</div><Sections sections={tab?.sections ?? []} /></>; }
function Sections({ sections }: { sections: ReturnType<typeof parseMarkdownSections> }) { return <>{sections.map((section, index) => <section key={`${section.heading}-${index}`}><h2>{section.heading}</h2>{section.paragraphs.map((paragraph, item) => <p key={item}>{paragraph}</p>)}<ul>{section.items.map((item, itemIndex) => <li key={itemIndex}>{item}</li>)}</ul></section>)}</>; }
